# for development

version: '3'
services:
  nimble-server:
    build:
      dockerfile: Dockerfile.dev
      context: ../server
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - '3001:3001'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
